[dns_cache]
dns-cache-01 ansible_host=172.16.1.44 ansible_user=icu01

# Pas ansible_host aan naar het IP-adres van jouw Ubuntu DNS caching server.
# Voorbeeld binnen jullie VLAN 425 Network Servers: 172.16.1.44
